---
abstract: 'type constraints with coercion to load the class'
author:
  - 'Toby Inkster (TOBYINK) <tobyink@cpan.org>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 6.17
dynamic_config: 0
generated_by: 'Dist::Inkt::Profile::TOBYINK version 0.013, CPAN::Meta::Converter version 2.120921'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Types-LoadableClass
no_index:
  directory:
    - eg
    - examples
    - inc
    - t
    - xt
optional_features: {}
provides:
  Types::LoadableClass:
    file: lib/Types/LoadableClass.pm
    version: 0.001
resources:
  X_identifier: http://purl.org/NET/cpan-uri/dist/Types-LoadableClass/project
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Types-LoadableClass
  homepage: https://metacpan.org/release/Types-LoadableClass
  license: http://dev.perl.org/licenses/
  repository: https://github.com/tobyink/p5-types-loadableclass
version: 0.001
x_contributors:
  - 'Dagfinn Ilmari Mannsåker (ILMARI) <ilmari@cpan.org>'
